import type { ChannelCapability } from "./channel-registry-types";

export const channelCapabilities: ChannelCapability[] = [
  {
    provider: "gmail",
    channel_type: "email",
    display_name: "Gmail",
    inbound_supported: true,
    outbound_supported: true,
    oauth_supported: true,
    manual_sync_supported: true,
    scheduler_supported: true,
    audit_supported: true,
    dashboard_status_supported: true,
    production_status: "available",
    safe_notes:
      "Gmail is the first supported channel; provider secrets and raw payloads are never exposed.",
  },
  {
    provider: "whatsapp",
    channel_type: "messaging",
    display_name: "WhatsApp",
    inbound_supported: false,
    outbound_supported: false,
    oauth_supported: false,
    manual_sync_supported: false,
    scheduler_supported: false,
    audit_supported: false,
    dashboard_status_supported: false,
    production_status: "planned",
    safe_notes: "Planned metadata only; no provider integration exists yet.",
  },
  {
    provider: "instagram",
    channel_type: "social",
    display_name: "Instagram",
    inbound_supported: false,
    outbound_supported: false,
    oauth_supported: false,
    manual_sync_supported: false,
    scheduler_supported: false,
    audit_supported: false,
    dashboard_status_supported: false,
    production_status: "planned",
    safe_notes: "Planned metadata only; no provider integration exists yet.",
  },
  {
    provider: "tiktok",
    channel_type: "social",
    display_name: "TikTok",
    inbound_supported: false,
    outbound_supported: false,
    oauth_supported: false,
    manual_sync_supported: false,
    scheduler_supported: false,
    audit_supported: false,
    dashboard_status_supported: false,
    production_status: "planned",
    safe_notes: "Planned metadata only; no provider integration exists yet.",
  },
  {
    provider: "webchat",
    channel_type: "webchat",
    display_name: "Webchat",
    inbound_supported: true,
    outbound_supported: false,
    oauth_supported: false,
    manual_sync_supported: false,
    scheduler_supported: false,
    audit_supported: false,
    dashboard_status_supported: false,
    production_status: "available",
    safe_notes:
      "Webchat inbound foundation is available; outbound replies and dashboard UI are not implemented yet.",
  },
];
